// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StatisticsAPP.Data;

#nullable disable

namespace StatisticsAPP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StatisticsAPP.Models.Auth.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Operations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ADD_USER",
                            Name = "إضافة مستخدم",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "EDIT_USER",
                            Name = "تعديل مستخدم",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "DELETE_USER",
                            Name = "حذف مستخدم",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("StatisticsAPP.Models.Auth.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ADMIN",
                            Name = "مدير النظام",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "JUDGE",
                            Name = "قاضٍ",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("StatisticsAPP.Models.Auth.RoleOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdOperation")
                        .HasColumnType("int");

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<int?>("OperationId")
                        .HasColumnType("int");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdOperation");

                    b.HasIndex("OperationId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.HasIndex("IdRole", "IdOperation")
                        .IsUnique();

                    b.ToTable("RoleOperations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdOperation = 1,
                            IdRole = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            IdOperation = 2,
                            IdRole = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            IdOperation = 3,
                            IdRole = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("StatisticsAPP.Models.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("Enable")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FullName")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 0,
                            Enable = true,
                            FullName = "مدير النظام",
                            Password = "ADMIN",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("StatisticsAPP.Models.Auth.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UserCreatedId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdRole");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId1");

                    b.HasIndex("UserId", "IdRole")
                        .IsUnique();

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdRole = 1,
                            UserCreatedId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("StatisticsAPP.Models.CircleModels.Circle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CircleTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<bool>("Enable")
                        .HasColumnType("bit");

                    b.Property<int>("IdType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CircleTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Circles");
                });

            modelBuilder.Entity("StatisticsAPP.Models.CircleModels.CircleJudge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CircleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCircle")
                        .HasColumnType("int");

                    b.Property<int>("IdJudge")
                        .HasColumnType("int");

                    b.Property<int?>("JudgeId")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CircleId");

                    b.HasIndex("IdCircle");

                    b.HasIndex("JudgeId");

                    b.HasIndex("UserId");

                    b.HasIndex("IdJudge", "IdCircle", "DateStart", "DateEnd")
                        .IsUnique()
                        .HasFilter("[DateEnd] IS NOT NULL");

                    b.ToTable("CircleJudges");
                });

            modelBuilder.Entity("StatisticsAPP.Models.CircleModels.CircleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CircleTypes");
                });

            modelBuilder.Entity("StatisticsAPP.Models.CourtsModels.SupCourt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SuperCourtId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SuperCourtId");

                    b.HasIndex("UserId");

                    b.ToTable("SupCourts");
                });

            modelBuilder.Entity("StatisticsAPP.Models.CourtsModels.SuperCourt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SuperCourts");
                });

            modelBuilder.Entity("StatisticsAPP.Models.DecisionModels.Decision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DecisionCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("IdDecisionCategory")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DecisionCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Decisions");
                });

            modelBuilder.Entity("StatisticsAPP.Models.DecisionModels.DecisionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DecisionCategories");
                });

            modelBuilder.Entity("StatisticsAPP.Models.DelayCasesModels.DelayCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DelayCasesCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("IdDelayCasesCategory")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DelayCasesCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("DelayCases");
                });

            modelBuilder.Entity("StatisticsAPP.Models.DelayCasesModels.DelayCasesCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DelayCasesCategories");
                });

            modelBuilder.Entity("StatisticsAPP.Models.InterCasesModels.InterCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdInterCasesCategory")
                        .HasColumnType("int");

                    b.Property<int?>("InterCasesCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InterCasesCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("InterCases");
                });

            modelBuilder.Entity("StatisticsAPP.Models.InterCasesModels.InterCasesCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("InterCasesCategories");
                });

            modelBuilder.Entity("StatisticsAPP.Models.JudgeModels.Judge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SeniorityNumber")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Judges");
                });

            modelBuilder.Entity("StatisticsAPP.Models.StatisticsModels.CircleStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DecisionsCount")
                        .HasColumnType("int");

                    b.Property<int>("DelayedCases")
                        .HasColumnType("int");

                    b.Property<int>("IdCircle")
                        .HasColumnType("int");

                    b.Property<int>("InterCasesCount")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CircleStatistics");
                });

            modelBuilder.Entity("StatisticsAPP.Models.StatisticsModels.StatisticsDecisions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("IdCircleStatistics")
                        .HasColumnType("int");

                    b.Property<int>("IdDecision")
                        .HasColumnType("int");

                    b.Property<int>("IdJudge")
                        .HasColumnType("int");

                    b.Property<int?>("JudgeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCircleStatistics");

                    b.HasIndex("IdDecision");

                    b.HasIndex("JudgeId");

                    b.HasIndex("UserId");

                    b.ToTable("StatisticsDecisions");
                });

            modelBuilder.Entity("StatisticsAPP.Models.StatisticsModels.StatisticsDelayCases", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int?>("DelayCaseId")
                        .HasColumnType("int");

                    b.Property<int>("IdCircleStatistics")
                        .HasColumnType("int");

                    b.Property<int>("IdDelayCase")
                        .HasColumnType("int");

                    b.Property<int>("IdJudge")
                        .HasColumnType("int");

                    b.Property<int?>("JudgeId")
                        .HasColumnType("int");

                    b.Property<int>("MonthDelay")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("YearDelay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DelayCaseId");

                    b.HasIndex("IdCircleStatistics");

                    b.HasIndex("JudgeId");

                    b.HasIndex("UserId");

                    b.ToTable("StatisticsDelayCases");
                });

            modelBuilder.Entity("StatisticsAPP.Models.StatisticsModels.StatisticsInterCases", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("IdCircleStatistics")
                        .HasColumnType("int");

                    b.Property<int>("IdInterCase")
                        .HasColumnType("int");

                    b.Property<int>("IdJudge")
                        .HasColumnType("int");

                    b.Property<int?>("InterCaseId")
                        .HasColumnType("int");

                    b.Property<int?>("JudgeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCircleStatistics");

                    b.HasIndex("InterCaseId");

                    b.HasIndex("JudgeId");

                    b.HasIndex("UserId");

                    b.ToTable("StatisticsInterCases");
                });

            modelBuilder.Entity("StatisticsAPP.Models.Auth.Operation", b =>
                {
                    b.HasOne("StatisticsAPP.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StatisticsAPP.Models.Auth.Role", b =>
                {
                    b.HasOne("StatisticsAPP.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StatisticsAPP.Models.Auth.RoleOperation", b =>
                {
                    b.HasOne("StatisticsAPP.Models.Auth.Operation", "Operation")
                        .WithMany()
                        .HasForeignKey("IdOperation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatisticsAPP.Models.Auth.Role", "Role")
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatisticsAPP.Models.Auth.Operation", null)
                        .WithMany("RoleOperations")
                        .HasForeignKey("OperationId");

                    b.HasOne("StatisticsAPP.Models.Auth.Role", null)
                        .WithMany("RoleOperations")
                        .HasForeignKey("RoleId");

                    b.HasOne("StatisticsAPP.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StatisticsAPP.Models.Auth.UserRole", b =>
                {
                    b.HasOne("StatisticsAPP.Models.Auth.Role", "Role")
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatisticsAPP.Models.Auth.Role", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId");

                    b.HasOne("StatisticsAPP.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatisticsAPP.Models.Auth.User", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId1");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StatisticsAPP.Models.CircleModels.Circle", b =>
                {
                    b.HasOne("StatisticsAPP.Models.CircleModels.CircleType", "CircleType")
                        .WithMany()
                        .HasForeignKey("CircleTypeId");

                    b.HasOne("StatisticsAPP.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CircleType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StatisticsAPP.Models.CircleModels.CircleJudge", b =>
                {
                    b.HasOne("StatisticsAPP.Models.CircleModels.Circle", null)
                        .WithMany("CircleJudges")
                        .HasForeignKey("CircleId");

                    b.HasOne("StatisticsAPP.Models.CircleModels.Circle", "Circle")
                        .WithMany()
                        .HasForeignKey("IdCircle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatisticsAPP.Models.JudgeModels.Judge", "Judge")
                        .WithMany()
                        .HasForeignKey("IdJudge")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatisticsAPP.Models.JudgeModels.Judge", null)
                        .WithMany("CircleJudges")
                        .HasForeignKey("JudgeId");

                    b.HasOne("StatisticsAPP.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Circle");

                    b.Navigation("Judge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StatisticsAPP.Models.CircleModels.CircleType", b =>
                {
                    b.HasOne("StatisticsAPP.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StatisticsAPP.Models.CourtsModels.SupCourt", b =>
                {
                    b.HasOne("StatisticsAPP.Models.CourtsModels.SuperCourt", "SuperCourt")
                        .WithMany()
                        .HasForeignKey("SuperCourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatisticsAPP.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SuperCourt");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StatisticsAPP.Models.CourtsModels.SuperCourt", b =>
                {
                    b.HasOne("StatisticsAPP.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StatisticsAPP.Models.DecisionModels.Decision", b =>
                {
                    b.HasOne("StatisticsAPP.Models.DecisionModels.DecisionCategory", "DecisionCategory")
                        .WithMany()
                        .HasForeignKey("DecisionCategoryId");

                    b.HasOne("StatisticsAPP.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DecisionCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StatisticsAPP.Models.DecisionModels.DecisionCategory", b =>
                {
                    b.HasOne("StatisticsAPP.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StatisticsAPP.Models.DelayCasesModels.DelayCase", b =>
                {
                    b.HasOne("StatisticsAPP.Models.DelayCasesModels.DelayCasesCategory", "DelayCasesCategory")
                        .WithMany()
                        .HasForeignKey("DelayCasesCategoryId");

                    b.HasOne("StatisticsAPP.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DelayCasesCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StatisticsAPP.Models.DelayCasesModels.DelayCasesCategory", b =>
                {
                    b.HasOne("StatisticsAPP.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StatisticsAPP.Models.InterCasesModels.InterCase", b =>
                {
                    b.HasOne("StatisticsAPP.Models.InterCasesModels.InterCasesCategory", "InterCasesCategory")
                        .WithMany()
                        .HasForeignKey("InterCasesCategoryId");

                    b.HasOne("StatisticsAPP.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterCasesCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StatisticsAPP.Models.InterCasesModels.InterCasesCategory", b =>
                {
                    b.HasOne("StatisticsAPP.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StatisticsAPP.Models.JudgeModels.Judge", b =>
                {
                    b.HasOne("StatisticsAPP.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StatisticsAPP.Models.StatisticsModels.CircleStatistics", b =>
                {
                    b.HasOne("StatisticsAPP.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StatisticsAPP.Models.StatisticsModels.StatisticsDecisions", b =>
                {
                    b.HasOne("StatisticsAPP.Models.StatisticsModels.CircleStatistics", "CircleStatistics")
                        .WithMany()
                        .HasForeignKey("IdCircleStatistics")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatisticsAPP.Models.DecisionModels.Decision", "Decision")
                        .WithMany()
                        .HasForeignKey("IdDecision")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatisticsAPP.Models.JudgeModels.Judge", "Judge")
                        .WithMany()
                        .HasForeignKey("JudgeId");

                    b.HasOne("StatisticsAPP.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CircleStatistics");

                    b.Navigation("Decision");

                    b.Navigation("Judge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StatisticsAPP.Models.StatisticsModels.StatisticsDelayCases", b =>
                {
                    b.HasOne("StatisticsAPP.Models.DelayCasesModels.DelayCase", "DelayCase")
                        .WithMany()
                        .HasForeignKey("DelayCaseId");

                    b.HasOne("StatisticsAPP.Models.StatisticsModels.CircleStatistics", "CircleStatistics")
                        .WithMany()
                        .HasForeignKey("IdCircleStatistics")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatisticsAPP.Models.JudgeModels.Judge", "Judge")
                        .WithMany()
                        .HasForeignKey("JudgeId");

                    b.HasOne("StatisticsAPP.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CircleStatistics");

                    b.Navigation("DelayCase");

                    b.Navigation("Judge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StatisticsAPP.Models.StatisticsModels.StatisticsInterCases", b =>
                {
                    b.HasOne("StatisticsAPP.Models.StatisticsModels.CircleStatistics", "CircleStatistics")
                        .WithMany()
                        .HasForeignKey("IdCircleStatistics")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatisticsAPP.Models.InterCasesModels.InterCase", "InterCase")
                        .WithMany()
                        .HasForeignKey("InterCaseId");

                    b.HasOne("StatisticsAPP.Models.JudgeModels.Judge", "Judge")
                        .WithMany()
                        .HasForeignKey("JudgeId");

                    b.HasOne("StatisticsAPP.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CircleStatistics");

                    b.Navigation("InterCase");

                    b.Navigation("Judge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StatisticsAPP.Models.Auth.Operation", b =>
                {
                    b.Navigation("RoleOperations");
                });

            modelBuilder.Entity("StatisticsAPP.Models.Auth.Role", b =>
                {
                    b.Navigation("RoleOperations");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("StatisticsAPP.Models.Auth.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("StatisticsAPP.Models.CircleModels.Circle", b =>
                {
                    b.Navigation("CircleJudges");
                });

            modelBuilder.Entity("StatisticsAPP.Models.JudgeModels.Judge", b =>
                {
                    b.Navigation("CircleJudges");
                });
#pragma warning restore 612, 618
        }
    }
}
